blueprint:
  name: Toggle lights based on motion and lux value
  description: Toogle a light based on motion sensing and the lux value in the room
  domain: automation
  author: Praneeth Behara
  input:
    light_target:
      name: Light
      selector:
        entity:
          domain:
            - light
    rgb_color:
      name: Light Color
      selector:
        color_rgb:
      default: [255, 255, 255]
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
            - binary_sensor
          device_class: motion
    lux_entity:
      name: Lux Value
      selector:
        entity:
          domain:
            - sensor
          device_class: illuminance
    lux_value:
      name: Lux Value
      description: The light will turn on if lux is below this value
      default: '50'
    wait_time:
      name: Wait Time
      description: Time to leave the light ON after no motion is detected
      selector:
        number:
          mode: slider
          min: 1
          max: 3600
          unit_of_measurement: seconds
      default: 60

mode: single

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0.25
    id: Detected
  - platform: state
    entity_id: !input motion_entity
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: !input wait_time
condition: []
action:
  - if:
      - condition: trigger
        id:
          - Detected
      - condition: numeric_state
        entity_id: !input lux_entity
        below: !input lux_value
    then:
      - service: light.turn_on
        data:
          rgb_color: !input rgb_color
        target:
          entity_id: !input light_target
    else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input light_target
